name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm test
    - run: npm run eslint
    - run: npm install -g web-ext # build tool
    - run: npm run build-chrome
    - run: npm run build-firefox
    - run: npm run build-firefox-mv3
